tests: unbreak native OSX tests
Summary:
D19731 broke the native OSX tests on CI because `self.conf3` is only defined if `self.have_ipv6` is `True`.
Move the offending line into the proper scope to fix this.

```
    ip3, port3 = self.conf3.addr
AttributeError: 'ProxyTest' object has no attribute 'conf3'
```

Test Plan:
land and see if CI is fixed

Tested locally by patching `test_ipv6_local` to always return false

Reviewers: #bitcoin_abc, Fabien

Reviewed By: #bitcoin_abc, Fabien

Differential Revision: https://reviews.bitcoinabc.org/D19734