add missing cstdint include in iguana_formatter.h
Summary:
I'm getting a compiler error without this include:
```
error: ‘uint8_t’ was not declared in this scope
```

Test Plan: `ninja`

Reviewers: #bitcoin_abc, Fabien

Reviewed By: #bitcoin_abc, Fabien

Differential Revision: https://reviews.bitcoinabc.org/D16897