[lint] fix a couple of PLE074 errors and enable PLE errors for RuffCheck
Summary:
A bare `raise` statement outside of an `except` clause is nonsensical.
```
$ python
Python 3.12.3 (main, Jun 19 2026, 12:46:00) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> raise
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: No active exception to reraise
```

Also remove an unreachabled `raise` that actually is in an `except` context but (after an `assert False`)

Add pylint errors to RuffCheck. These all indicate actual bugs. See https://docs.astral.sh/ruff/rules/#error-ple

Depends on D20293

Test Plan:
```
arc lint --everything

cmake .. -GNinja -DBUILD_CHRONIK=1
ninja check-functional
```

Reviewers: #bitcoin_abc, Fabien

Reviewed By: #bitcoin_abc, Fabien

Differential Revision: https://reviews.bitcoinabc.org/D20298