tests: fix formatting of itemid in p2p_inv_download
Summary:
This new test  added in D16668 caused intermittent failures when the itemid hex representation started with a `0`

```
AssertionError: [node 0] Expected messages "['received getdata (1 invsz)', 'received getdata for: 0x1f000002 8cbfe7dca09271f2d028790ae71770b1b4a6263e88fa0bf9e29ab118be195ea']" does not partially match log:

    - 2024-08-27T20:02:23.029782Z [../../src/net_processing.cpp:5330] [ProcessMessage] received getdata for: 0x1f000002 08cbfe7dca09271f2d028790ae71770b1b4a6263e88fa0bf9e29ab118be195ea peer=1
```
Use the `uint256_hex` helper function to properly format the inv id.

Test Plan: `ninja check-functional`

Reviewers: #bitcoin_abc, roqqit

Reviewed By: roqqit

Differential Revision: https://reviews.bitcoinabc.org/D16688